# GitHub Action to generate a contribution graph with a snake animation.

name: Snake Game

# Controls when the action will run. It runs every Monday at 12AM UTC.
on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at 12AM UTC

  # Allows running the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Contribution Graph
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake contribution animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      # Step 3: Upload the generated SVG/GIF as artifacts
      - name: Upload Snake Graph Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: snake-graph
          path: dist

      # Step 4: Commit and push the generated files to the `output` branch
      - name: Push Snake Animation to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output  # Saves the generated snake animation in the `output` branch
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
