name: Snake Game

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC

  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  generate:
    name: Generate Snake Contribution Graph
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake contribution animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
           # GitHub username to generate the animation for
          github_user_name: ${{ github.repository_owner }}  # 🔹 Set your GitHub username explicitly
          # Define the output files and their configurations
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif

      # Step 3: Upload the generated SVG/GIF as artifacts
      - name: Upload Snake Graph Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: snake-graph
          path: dist

      # Step 4: Push Snake Animation to GitHub Pages
      - name: Deploy Snake Animation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output  # Saves the animation in the `output` branch
          publish_dir: dist  # Ensure correct directory is uploaded
          commit_message: "🐍 Update snake animation [skip ci]"
